import {
  BillingPeriod,
  CurrencyCode,
  PaymentMethod,
  Subscription,
  SubscriptionStatus,
} from '../../subscriptions/entities/subscriptions.entity.js';

export type SubscriptionSeed = Pick<
  Subscription,
  | 'name'
  | 'currency'
  | 'startDate'
  | 'renewAfterTrial'
  | 'cancelAtPeriodEnd'
  | 'status'
> &
  Partial<
    Pick<
      Subscription,
      | 'price'
      | 'billingPeriod'
      | 'nextBillingDate'
      | 'trial_end_date'
      | 'paymentMethod'
    >
  >;

function date(value: string): Date {
  return new Date(`${value}T00:00:00.000Z`);
}

export function createSubscriptionSeeds(): SubscriptionSeed[] {
  return [
    {
      name: 'Netflix Standard',
      price: '13.49',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-01-15'),
      nextBillingDate: date('2026-10-15'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Spotify Premium',
      price: '11.12',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-03-01'),
      nextBillingDate: date('2026-11-01'),
      paymentMethod: PaymentMethod.PAYPAL,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Adobe Creative Cloud',
      price: '779.88',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-06-10'),
      nextBillingDate: date('2027-06-10'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Notion Plus',
      price: '9.50',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-08-20'),
      nextBillingDate: date('2026-10-20'),
      paymentMethod: PaymentMethod.GOOGLE_PAY,
      renewAfterTrial: false,
      cancelAtPeriodEnd: true,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'OVHcloud VPS',
      price: '95.88',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-07-05'),
      nextBillingDate: date('2027-07-05'),
      paymentMethod: PaymentMethod.PAYPAL,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Basic-Fit Comfort',
      price: '24.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2025-09-01'),
      paymentMethod: PaymentMethod.PREPAY_CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.CANCELLED,
    },
    {
      name: 'Le Monde Numérique',
      price: '119.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-09-25'),
      trial_end_date: date('2026-10-09'),
      paymentMethod: PaymentMethod.APPLE_PAY,
      renewAfterTrial: true,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.TRIAL,
    },
    {
      name: 'Figma Professional Trial',
      currency: CurrencyCode.EUR,
      startDate: date('2026-10-01'),
      trial_end_date: date('2026-10-15'),
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.TRIAL,
    },
    {
      name: 'iCloud+',
      price: '2.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-02-12'),
      nextBillingDate: date('2026-10-12'),
      paymentMethod: PaymentMethod.APPLE_PAY,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Disney+ Premium',
      price: '139.90',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-04-03'),
      nextBillingDate: date('2027-04-03'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Amazon Prime',
      price: '69.90',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-05-18'),
      nextBillingDate: date('2027-05-18'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'YouTube Premium',
      price: '12.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-02-08'),
      nextBillingDate: date('2026-10-08'),
      paymentMethod: PaymentMethod.GOOGLE_PAY,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Canal+ Ciné Séries',
      price: '29.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-01-22'),
      nextBillingDate: date('2026-10-22'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: true,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Microsoft 365 Personnel',
      price: '99.00',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-03-14'),
      nextBillingDate: date('2027-03-14'),
      paymentMethod: PaymentMethod.PAYPAL,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Google One 200 Go',
      price: '2.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-06-11'),
      nextBillingDate: date('2026-10-11'),
      paymentMethod: PaymentMethod.GOOGLE_PAY,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Dropbox Plus',
      price: '119.88',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-08-02'),
      nextBillingDate: date('2027-08-02'),
      paymentMethod: PaymentMethod.PAYPAL,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'GitHub Copilot Pro',
      price: '10.00',
      currency: CurrencyCode.USD,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-05-19'),
      nextBillingDate: date('2026-10-19'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'ChatGPT Plus',
      price: '20.00',
      currency: CurrencyCode.USD,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-07-24'),
      nextBillingDate: date('2026-10-24'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Claude Pro',
      price: '20.00',
      currency: CurrencyCode.USD,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-09-27'),
      nextBillingDate: date('2026-10-27'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'JetBrains All Products Pack',
      price: '289.00',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-02-17'),
      nextBillingDate: date('2027-02-17'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: '1Password Individual',
      price: '35.88',
      currency: CurrencyCode.USD,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-06-26'),
      nextBillingDate: date('2027-06-26'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'NordVPN Plus',
      price: '59.88',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-01-30'),
      nextBillingDate: date('2027-01-30'),
      paymentMethod: PaymentMethod.PAYPAL,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Deezer Premium',
      price: '11.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-04-13'),
      nextBillingDate: date('2026-10-13'),
      paymentMethod: PaymentMethod.PAYPAL,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Apple TV+',
      price: '9.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-08-16'),
      nextBillingDate: date('2026-10-16'),
      paymentMethod: PaymentMethod.APPLE_PAY,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Nintendo Switch Online',
      price: '19.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-05-09'),
      nextBillingDate: date('2027-05-09'),
      paymentMethod: PaymentMethod.PREPAY_CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'PlayStation Plus Essential',
      price: '71.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-03-28'),
      nextBillingDate: date('2027-03-28'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: true,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Strava Premium',
      price: '69.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-07-21'),
      nextBillingDate: date('2027-07-21'),
      paymentMethod: PaymentMethod.APPLE_PAY,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Free Mobile 5G',
      price: '19.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2025-11-10'),
      nextBillingDate: date('2026-10-10'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Orange Fibre',
      price: '39.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-02-25'),
      nextBillingDate: date('2026-10-25'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'SNCF MAX JEUNE',
      price: '79.00',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-04-29'),
      nextBillingDate: date('2026-10-29'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: true,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Mediapart',
      price: '11.00',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-09-18'),
      nextBillingDate: date('2026-10-18'),
      paymentMethod: PaymentMethod.PAYPAL,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'Duolingo Super',
      price: '89.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-08-07'),
      nextBillingDate: date('2027-08-07'),
      paymentMethod: PaymentMethod.GOOGLE_PAY,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.ACTIVE,
    },
    {
      name: 'LinkedIn Premium Career',
      price: '39.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.MONTHLY,
      startDate: date('2026-01-06'),
      paymentMethod: PaymentMethod.CARD,
      renewAfterTrial: false,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.CANCELLED,
    },
    {
      name: 'Headspace Trial',
      price: '57.99',
      currency: CurrencyCode.EUR,
      billingPeriod: BillingPeriod.YEARLY,
      startDate: date('2026-10-03'),
      trial_end_date: date('2026-10-17'),
      paymentMethod: PaymentMethod.APPLE_PAY,
      renewAfterTrial: true,
      cancelAtPeriodEnd: false,
      status: SubscriptionStatus.TRIAL,
    },
  ];
}
